inherit_gem:
  armitage-rubocop:
    - lib/rubocop.general.yml
    - lib/rubocop.rake.yml
    - lib/rubocop.rspec.yml

AllCops:
  TargetRubyVersion: 3.0.0
  NewCops: enable
  Include:
    - lib/**/*.rb
    - spec/**/*.rb
    - Gemfile
    - Rakefile
    - smart_types.gemspec
    - bin/console

# NOTE: support for old ruby versions
Style/RedundantBegin:
  Enabled: false

# NOTE: used only in specs and it is ok in specs
Lint/EmptyBlock:
  Enabled: false

# NOTE: too situative and too subjective
Naming/VariableNumber:
  Enabled: false
